import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/cart_provider.dart';
import '../services/function_service.dart';
import 'order_confirmation_screen.dart';
class CheckoutScreen extends StatefulWidget{const CheckoutScreen({super.key});@override State<CheckoutScreen> createState()=>_CheckoutScreenState();}
class _CheckoutScreenState extends State<CheckoutScreen>{String method='cod';bool busy=false;Future<Map<String,dynamic>> address()async{final u=FirebaseAuth.instance.currentUser!.uid;final s=await FirebaseFirestore.instance.collection('users/$u/addresses').limit(1).get();if(s.docs.isEmpty)throw Exception('Add a delivery address first');return s.docs.first.data();}Future<void> place()async{final p=context.read<CartProvider>();setState(()=>busy=true);try{final id=await FunctionService().placeOrder(items:p.items,address:await address(),paymentMethod:method,discount:p.discount);if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>OrderConfirmationScreen(orderId:id,total:p.total)),(r)=>r.isFirst);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Checkout')),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Payment method',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),RadioListTile(value:'cod',groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:const Text('Cash on Delivery')),RadioListTile(value:'razorpay_test',groupValue:method,onChanged:(v)=>setState(()=>method=v!),title:const Text('Online payment (Razorpay test mode)')),const SizedBox(height:20),FilledButton(onPressed:busy?null:place,child:Text(busy?'Placing order…':'Place order'))]));}
