import 'package:flutter/material.dart';
import '../services/auth_service.dart';

class OnboardingScreen extends StatefulWidget { const OnboardingScreen({super.key}); @override State<OnboardingScreen> createState() => _OnboardingScreenState(); }
class _OnboardingScreenState extends State<OnboardingScreen> {
  final page = PageController(); int index = 0;
  final slides = const [('Fresh groceries', 'Everything you need, delivered from trusted stores.', Icons.local_grocery_store_rounded), ('Hot meals', 'Order delicious food from your favourite local restaurants.', Icons.restaurant_rounded), ('Fast delivery', 'Track your order and enjoy doorstep delivery.', Icons.delivery_dining_rounded)];
  void finish() async { await AuthService.instance.markOnboardingSeen(); if (mounted) Navigator.pushReplacementNamed(context, '/login'); }
  @override Widget build(BuildContext context) => Scaffold(body: SafeArea(child: Column(children: [Expanded(child: PageView.builder(controller: page, itemCount: slides.length, onPageChanged: (v) => setState(() => index = v), itemBuilder: (_, i) => Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Icon(slides[i].$3, size: 130, color: Theme.of(context).colorScheme.primary), const SizedBox(height: 35), Text(slides[i].$1, style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 12), Padding(padding: const EdgeInsets.symmetric(horizontal: 40), child: Text(slides[i].$2, textAlign: TextAlign.center))]))), Row(mainAxisAlignment: MainAxisAlignment.center, children: List.generate(slides.length, (i) => AnimatedContainer(duration: const Duration(milliseconds: 200), margin: const EdgeInsets.all(4), width: i == index ? 24 : 8, height: 8, decoration: BoxDecoration(color: i == index ? Theme.of(context).colorScheme.primary : Colors.grey, borderRadius: BorderRadius.circular(8))))), Padding(padding: const EdgeInsets.all(24), child: SizedBox(width: double.infinity, child: FilledButton(onPressed: index == slides.length - 1 ? finish : () => page.nextPage(duration: const Duration(milliseconds: 300), curve: Curves.easeInOut), child: Text(index == slides.length - 1 ? 'Get Started' : 'Next'))))])));
}
