import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,getDocs,query,orderBy,limit,doc,updateDoc} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const firebaseConfig={apiKey:'REPLACE',authDomain:'REPLACE',projectId:'REPLACE',storageBucket:'REPLACE',messagingSenderId:'REPLACE',appId:'REPLACE'};
const auth=getAuth(initializeApp(firebaseConfig)),db=getFirestore();const root=document.querySelector('#app');let active='dashboard';const pages=['dashboard','orders','products','categories','coupons','reviews'];
function login(){root.innerHTML='<div class="login card"><h1>FreshCart Admin</h1><input id="email" placeholder="Admin email"><input id="pass" type="password" placeholder="Password"><button id="go">Sign in</button><p id="error"></p></div>';go.onclick=async()=>{try{await signInWithEmailAndPassword(auth,email.value,pass.value)}catch(e){error.textContent='Login failed'}}}
async function rows(name){return(await getDocs(query(collection(db,name),orderBy(name==='orders'?'createdAt':'name','desc'),limit(100)))).docs.map(d=>({id:d.id,...d.data()}))}
async function render(){root.innerHTML='<div class="shell"><aside class="side"><h2>FreshCart</h2>'+pages.map(x=>`<button data-page="${x}">${x}</button>`).join('')+'<button id="logout">Logout</button></aside><main class="main"><h1>'+active+'</h1><section id="content">Loading…</section></main></div>';document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{active=b.dataset.page;render()});logout.onclick=()=>signOut(auth);const e=document.querySelector('#content');if(active==='dashboard'){const[o,u,p]=await Promise.all([rows('orders'),rows('users'),rows('products')]);e.innerHTML=`<div class="cards"><div class="card">Orders: <b>${o.length}</b></div><div class="card">Users: <b>${u.length}</b></div><div class="card">Products: <b>${p.length}</b></div></div>`}else{const d=await rows(active);e.innerHTML=`<table><tr><th>ID</th><th>Value</th><th>Action</th></tr>${d.map(x=>`<tr><td>${x.id}</td><td>${x.name||x.status||x.code||x.comment||''}</td><td>${active==='orders'?`<select data-id="${x.id}"><option>placed</option><option>confirmed</option><option>packed</option><option>out_for_delivery</option><option>delivered</option><option>cancelled</option></select>`:'—'}</td></tr>`).join('')}</table>`;e.querySelectorAll('select').forEach(s=>s.onchange=()=>updateDoc(doc(db,'orders',s.dataset.id),{status:s.value}))}}
onAuthStateChanged(auth,u=>u?render():login());
